# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# Note: currently 'libwebp-dev' is not white-listed on Travis hence we need sudo.
# See https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#sudo: false
#addons:
#  apt:
#    packages:
#      - libwepb-dev
#      - libpoppler-cpp-dev

before_install:
  - sudo add-apt-repository -y ppa:lyrasis/precise-backports
  - sudo apt-get update -q
  - sudo apt-get install -y libwebp-dev libpoppler-cpp-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
